sudo: false

language: rust

matrix:
  include:
    - rust: 1.30.0
      env: RUSTFLAGS="--cfg no_raw_identifiers"
      script: cargo test
    - rust: stable
      env: RUSTFLAGS="--cfg no_raw_identifiers"
      script: cargo test
    - rust: beta
      env: RUSTFLAGS="--cfg no_raw_identifiers"
      script: cargo test
    - rust: nightly
      script: cargo test
